In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [3]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])

10


In [4]:
print(arr[2])

30


In [5]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr.size)

5


In [6]:
print(arr.ndim)

1


In [7]:
print(arr.shape)

(5,)


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr+10)

[11 12 13 14 15]


In [9]:
print(arr*2)

[ 2  4  6  8 10]


In [10]:
print(arr.shape)

(5,)


In [11]:
print(arr**2)

[ 1  4  9 16 25]


In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [3]:
import numpy as np
print(np.random.rand())

0.6597486929165685


In [4]:
print(np.random.rand(5))

[0.07381815 0.43888503 0.87587024 0.497973   0.63821994]


In [5]:
import numpy as np
print(np.random.randn())

-1.3690204793845695


In [6]:
print(np.random.randn(5))

[ 1.05812712  1.87647425  0.20314027 -0.75443587  0.60677671]


In [8]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr.dtype)

int64


In [9]:
import numpy as np
arr=np.array([10.5,20.2,30.8])
print(arr.dtype)

float64


In [10]:
import numpy as np
arr=np.array(["Apple","Mango","Orange"])
print(arr.dtype)

<U6


In [11]:
import numpy as np
arr=np.array([True, False, True])
print(arr.dtype)

bool


# Convert Datatypes

In [12]:
import numpy as np
arr=np.array([10, 20, 30])
new_arr= arr.astype(float)
print(new_arr)
print(new_arr.dtype)

[10. 20. 30.]
float64


# Operations on Array

In [13]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [14]:
a-b

array([-3, -3, -3])

In [15]:
a*b

array([ 4, 10, 18])

In [16]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# Matrix Multiplication

In [17]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [26]:
A@B

array([[19, 22],
       [43, 50]])

# Aggregations

In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr.sum()

np.int64(10)

In [21]:
arr.mean()

np.float64(2.5)

In [22]:
arr.max()

np.int64(4)

In [23]:
arr.min()

np.int64(1)

In [24]:
arr.std()

np.float64(1.118033988749895)

In [25]:
import numpy as np

arr = np.array([1,2,3,4])

print("Array:", arr)

print("Sum =", arr.sum())
print("Mean =", arr.mean())
print("Max =", arr.max())
print("Min =", arr.min())
print("Std =", arr.std())

Array: [1 2 3 4]
Sum = 10
Mean = 2.5
Max = 4
Min = 1
Std = 1.118033988749895


# Indexing and Slicing


In [27]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr[0]

np.int64(1)

In [28]:
arr[1]

np.int64(2)

In [29]:
arr[-1]

np.int64(5)

# 1D Array
syntax

In [30]:
# arr[start:end]

In [31]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr[0]

np.int64(1)

In [32]:
arr[1:4]

array([2, 3, 4])

In [33]:
arr[:3]

array([1, 2, 3])

In [34]:
arr[::2]

array([1, 3, 5])

# 2D Array


In [36]:
# arr[row,column]

In [35]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]

np.int64(2)

In [37]:
arr[:, 1]

array([2, 5])

In [38]:
arr[1, :2]

array([4, 5])

# Boolean Indexing

In [40]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
mask = arr>3
arr[mask]

array([4, 5])

# Reshaping and combining Arrays

In [41]:
import numpy as np
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
import numpy as np
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [43]:
import numpy as np
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

# Broadcasting

In [44]:
import numpy as np
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])